collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6510639
  brandStrength: 0.5085106
  lightness: 0.6617022
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
  rhythmicContrast: 0
typography_spectrum: 0.8914894
layout_spectrum: 0.7531915
name: 'atom:matiQ'
